# Template: replace age1REPLACE_WITH_REAL_PUBLIC_KEY with your own age public key before encrypting secrets.
creation_rules:
  - path_regex: secrets/.*\.yaml
    key_groups:
      - age:
          # REPLACE THIS WITH THE USER'S ACTUAL age PUBLIC KEY
          - age1REPLACE_WITH_REAL_PUBLIC_KEY
